### ISSUE TITLE
Vue2 support

### ISSUE THREAD

**Issue by liuya00** [open-data-plan/g2plot-vue#1]
Hi, 
Just a question, want to know whether g2plot-vue can be used for vue2.

**Comment by kagawagao** [comment]
Not support not yet
`g2plot-vue` used `defineComponent` which shipped with vue 3 to create component.

Vue 2 support maybe comming in later days

**Comment by liuya00** [comment]
ok fine

**Comment by kagawagao** [comment]
supported in `v3.0.0`
