### ISSUE TITLE
[Bug]饼图label设置为spider蜘蛛不生效

### ISSUE THREAD

**Issue by xiaochong44** [open-data-plan/g2plot-vue#168]
**Describe the bug**
饼图label设置为spider蜘蛛不生效
设置如下
label: {
    type: 'spider',
    content: '{name} {percentage} {value}',
  }

**Comment by kagawagao** [comment]
麻烦给一下可复现的 demo

**Comment by kagawagao** [comment]
demo: https://github.com/open-data-plan/g2plot-vue2-demo/blob/master/src/components/pie-chart.vue

**Comment by xiaochong44** [comment]
vue 3.05
@antv/g2plot 2.3.11
@opd/g2plot-vue 3.1.5
源代码
let config: PieChartProps = {
        //autoFit: true,
        data: data.value,
        colorField: '月份',
        angleField: '月均降雨量',
        radius: props.radius / 100,
        supportCSSTransform: true,
        chartRef: chart,
        padding: 'auto',
        label: {
          type: 'spider',
          content: '{name} {percentage} {value}',
        },
      };
<PieChart {...this.config} />

**Comment by kagawagao** [comment]
> vue 3.05
> @antv/g2plot 2.3.11
> @opd/g2plot-vue 3.1.5
> 源代码
> let config: PieChartProps = {
> //autoFit: true,
> data: data.value,
> colorField: '月份',
> angleField: '月均降雨量',
> radius: props.radius / 100,
> supportCSSTransform: true,
> chartRef: chart,
> padding: 'auto',
> label: {
> type: 'spider',
> content: '{name} {percentage} {value}',
> },
> };
> <PieChart {...this.config} />

看下上面的 demo，demo 是 vue 2 的，但是配置是一样的

**Comment by xiaochong44** [comment]
奇怪，我的怎么不生效，问题出在哪，我的配置也没有错，我用的是tsx
设置成inner和outer都生效，就spider不生效

**Comment by kagawagao** [comment]
@xiaochong44  tsx 的demo https://github.com/open-data-plan/g2plot-vue-demo
