### ISSUE TITLE
tooltip 能否支持 vue 组件？

### ISSUE THREAD

**Issue by wulucxy** [open-data-plan/g2plot-vue#170]
目前 g2-plot 只支持 字符串，实际使用肯定还是以组件为主

**Comment by kagawagao** [comment]
因为底层的 `@antv/g2plot`，甚至更底层的 `g2` 只支持 html 字符串，而 `@opd/g2plot-vue` 只是在此基础上提供了 vue 组件，不提供其他能力。

后续可能会提供一个支持 vue 组件的方案，但只是可能。
