### ISSUE TITLE
beforeUpdate not changed after attrs changes

### ISSUE THREAD

**Issue by wulucxy** [open-data-plan/g2plot-vue#203]
**Describe the bug**
目前组件属性完全透传，从组件上来说开发可能完全复用，但是会导致 beforeUpdate 不会触发。

举例（vue: 2.6.10）：

```
<LineChart :data="state.data" v-bind="state.lineChartConfig" />

setup(props) {
    const state = reactive({
      lineChartConfig: {},
      data: [],
    });
    watch(() => props.stageData, next => {
      state.lineChartConfig = {...next.config};
      state.data = next.data;
    });
```
异步加载组件参数后，尽管 `data` 发生了变更，但是不会触发 `beforeUpdate`，组件参数只能在 mounted 生效。与预期不相符

**To Reproduce**

**Expected behavior**
`attrs` 变更触发 `beforeUpdate` 正常执行 

**Desktop (please complete the following information):**

- OS: macOS
- `@antv/g2plot` Version v2.3.17
- `@opd/g2plot-vue` Version： v3.1.5
- `vue` Version：2.6.10

**Additional context**

**Comment by wulucxy** [comment]
实践下来 vue 3 没有这个问题，是不是意味着 vue3 `attrs` 变更会触发  `rerender`，但是 vue 2 不会触发 `rerender`？

**Comment by kagawagao** [comment]
可以查看最新的 [vue 2 demo](https://g2plot-vue2-demo-opd.vercel.app/) 看效果

**Comment by wulucxy** [comment]
优秀
