### ISSUE TITLE
在vite使用时需要单独入@babel/runtime

### ISSUE THREAD

**Issue by levi-Ma** [open-data-plan/g2plot-vue#293]
在vite使用时需要单独入@babel/runtime；
以下是报错提示：
> node_modules/@opd/g2plot-vue/es/utils.js:1:26: error: Could not resolve "@babel/runtime/helpers/esm/objectSpread2" (mark it as external to exclude it from the bundle)
    1 │ ...tSpread from "@babel/runtime/helpers/esm/objectSpread2";

**Comment by kagawagao** [comment]
add `@babel/runtime` to peer deps, up with workspace version

but `@babel/runtime` still needs to be installed
