### ISSUE TITLE
[Feature] 请问G2plot 新增的violin,stock等图是否能涵盖？

### ISSUE THREAD

**Issue by loongmxbt** [open-data-plan/g2plot-vue#299]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

请问G2plot 新增的violin,stock等图是否能涵盖？
https://g2plot.antv.vision/en/examples/more-plots/violin#basic
https://g2plot.antv.vision/en/examples/gallery#category-Stock

**Comment by kagawagao** [comment]
`StockChart` 已经是支持的

https://github.com/open-data-plan/g2plot-vue/blob/24041b15f21d571f05a5bd2b701da01a63ccaee7/src/index.ts#L114

最新的图表已经同步了，但是 `ViolinChart` 的测试用例没过，所以还没更新代码

**Comment by loongmxbt** [comment]
多谢大佬 Violin Chart 已经成功运行

**Comment by kagawagao** [comment]
> 多谢大佬 Violin Chart 已经成功运行

大佬谈不上，好用的话给个 star 😄
