### ISSUE TITLE
[Bug] unable to resolve dependency tree

### ISSUE THREAD

**Issue by ndrshn** [open-data-plan/g2plot-vue#368]
**Describe the bug**
Cannot install package via npm. It gives "unable to resolve dependency tree" error.

**To Reproduce**
1.
```js
npm i @opd/g2plot-vue
```

**Expected behavior**
A clean installation 

**Screenshots**
none

- OS: win 10
- Browser: chrome v92.0.4515.107
- `@antv/g2plot` Version v2.3.18
- `@opd/g2plot-vue` Version couldn't detected due to installation error.
- `vue` Version v3.1.1

**Comment by kagawagao** [comment]
can you provide a mini showcase or terminal output

**Comment by Robert-Ro** [comment]
link this:
```
npm ERR! Found: vue@3.1.5
npm ERR! node_modules/vue
npm ERR!   vue@"^3.1.3" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from @opd/g2plot-vue@3.4.0
npm ERR!   node_modules/@opd/g2plot-vue
npm ERR!     dev @opd/g2plot-vue@"^3.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.5
npm ERR! node_modules/@vue/composition-api
npm ERR!   peerOptional @vue/composition-api@"^1.0.0-rc.2" from @opd/g2plot-vue@3.4.0
npm ERR!   node_modules/@opd/g2plot-vue
npm ERR!     dev @opd/g2plot-vue@"^3.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /var/lib/jenkins/.npm/eresolve-report.txt for a full report.
```

**Comment by kagawagao** [comment]
`g2plot-vue`is build  for both `vue` `v2` and `v3`
So if you use `vue@3.x` in your project, there is no need `@vue/composition-api`to be installed
Otherwise,  you should install it.

**Comment by Robert-Ro** [comment]
I don't install `@vue/composition-api` manually, and it's only reproduce in jenkins env(npm), not local development(yarn 1.22).
fix with add package-lock.json to git, confusing 😔

**Comment by kagawagao** [comment]
lock file is important in CI
