### ISSUE TITLE
我用vite 安装后，提示[G2Plot-Vue] Switch main field for Vue 3

### ISSUE THREAD

**Issue by CedarXi** [open-data-plan/g2plot-vue#439]
我用vite 安装后，提示[G2Plot-Vue] Switch main field for Vue 3

然后我用了 node ./node_modules/@opd/g2plot-vue/scripts/postinstall.js

还是提示 [G2Plot-Vue] Switch main field for Vue 3

**Comment by kagawagao** [comment]
使用的 `vue` 版本是多少呢，如果依赖了 `v3`，那么这个就是正确的，可以 `npm ls vue` 看一下

**Comment by chengbenchao** [comment]
> 我用vite 安装后，提示[G2Plot-Vue] Switch main field for Vue 3
> 
> 然后我用了 node ./node_modules/@opd/g2plot-vue/scripts/postinstall.js
> 
> 还是提示 [G2Plot-Vue] Switch main field for Vue 3



> 我用vite 安装后，提示[G2Plot-Vue] Switch main field for Vue 3
> 
> 然后我用了 node ./node_modules/@opd/g2plot-vue/scripts/postinstall.js
> 
> 还是提示 [G2Plot-Vue] Switch main field for Vue 3

你好，我也是一样的问题，怎么解决
