### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by whiletrueluna** [open-data-plan/g2plot-vue#457]
使用LineChart时遇到这个问题<img width="557" alt="Screen Shot 2021-09-24 at 4 53 59 PM" src="https://user-images.githubusercontent.com/82555050/134647853-d206ed72-3716-4bb9-a582-63325424bae7.png">
- OS: macOS
- Browser chrome
- `@antv/g2plot` Version [v2.3.13]
- `@opd/g2plot-vue` Version [v3.1.12]
- `vue` Version [v2.6.12]

**Comment by kagawagao** [comment]
@whiletrueluna 方便给一个可复现的 demo 吗

**Comment by whiletrueluna** [comment]
> @whiletrueluna 方便给一个可复现的 demo 吗

这个有点难，但是有一个很奇怪的地方我截图给您看一下
<img width="658" alt="Screen Shot 2021-09-24 at 5 09 15 PM" src="https://user-images.githubusercontent.com/82555050/134649714-f10fd25a-419e-43c5-ac2e-c29f69bf011c.png">
<img width="406" alt="Screen Shot 2021-09-24 at 5 11 45 PM" src="https://user-images.githubusercontent.com/82555050/134649838-7b97a096-11e7-4b6f-a475-a2570613ed06.png">

**Comment by kagawagao** [comment]
> > @whiletrueluna 方便给一个可复现的 demo 吗
> 
> 这个有点难，但是有一个很奇怪的地方我截图给您看一下
> <img alt="Screen Shot 2021-09-24 at 5 09 15 PM" width="658" src="https://user-images.githubusercontent.com/82555050/134649714-f10fd25a-419e-43c5-ac2e-c29f69bf011c.png">
> <img alt="Screen Shot 2021-09-24 at 5 11 45 PM" width="406" src="https://user-images.githubusercontent.com/82555050/134649838-7b97a096-11e7-4b6f-a475-a2570613ed06.png">

原因在于，图表实际是在组件 `mounted` 之后才渲染的

https://github.com/open-data-plan/g2plot-vue/blob/2ea620dc27e499cf0629a450e2d283785f05e2c5/src/components/base.tsx#L65-L77

所以在 `mounted` 这个声明周期里通过 `chartRef.value` 来获得图表实例是没有

**Comment by kagawagao** [comment]
@whiletrueluna 新增 `onReady` 回调，可以在这里即时的拿到图表实例

https://github.com/open-data-plan/g2plot-vue/blob/9c0cc7e60a5504430d3deb9bfd2ca771543d8ffd/src/components/base.tsx#L67-L80

https://github.com/open-data-plan/g2plot-vue/blob/9c0cc7e60a5504430d3deb9bfd2ca771543d8ffd/__tests__/plots/line.spec.tsx#L7-L15

**Comment by whiletrueluna** [comment]
> @whiletrueluna 新增 `onReady` 回调，可以在这里即时的拿到图表实例
> 
> https://github.com/open-data-plan/g2plot-vue/blob/9c0cc7e60a5504430d3deb9bfd2ca771543d8ffd/src/components/base.tsx#L67-L80
> 
> https://github.com/open-data-plan/g2plot-vue/blob/9c0cc7e60a5504430d3deb9bfd2ca771543d8ffd/__tests__/plots/line.spec.tsx#L7-L15

好的，谢谢！

**Comment by Lruihao** [comment]
@kagawagao 请问 vue2 里面怎么调用 `onReady`
