### ISSUE TITLE
[Bug]3.6.0版本作用于Vue2会报错，template or render function not defined

### ISSUE THREAD

**Issue by vvyman** [open-data-plan/g2plot-vue#483]
**Bug具体情况**
3.6.0版本是否对Vue2不支持？按照demo方式引入依旧报错，
> [Vue warn]: Failed to mount component: template or render function not defined.

**依赖版本列表**
```
"dependencies": {
    "@antv/g2plot": "^2.3.35",
    "@opd/g2plot-vue": "3.5.0",
    "axios": "^0.21.1",
    "core-js": "^3.9.0",
    "echarts": "^4.5.0",
    "vue": "^2.6.12",
    "vue-echarts": "^4.1.0",
    "vue-fullpage.js": "^0.1.7",
    "vue-router": "^3.5.1",
    "vuex": "~2.3.1"
  },
"devDependencies": {
    "@babel/core": "^7.13.1",
    "@babel/preset-env": "^7.13.0",
    "@vue/babel-preset-jsx": "^1.2.4",
    "@vue/composition-api": "^1.0.0-rc.3",
    "assert": "^2.0.0",
    "autoprefixer": "^9.1.5",
    "babel-loader": "^8.2.2",
    "babel-plugin-import": "^1.13.3",
    "vue-loader": "^15.9.6",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^4.25.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.10.1"
    ...
  }
```

**暂时有效方案**
使用Demo中的3.1.12版本

**Comment by kagawagao** [comment]
demo 更新版本之后未发现该问题，方便给一个可复现的 demo 吗

https://github.com/open-data-plan/g2plot-vue2-demo/commit/7e1b25a353cd9c6dcff105b57c5e5eb6e811074b

**Comment by vvyman** [comment]
你好，具体配置如下，https://codesandbox.io/s/sweet-snow-66p0s?file=/package.json

**Comment by vvyman** [comment]
> demo 更新版本之后未发现该问题，方便给一个可复现的 demo 吗
> 
> [open-data-plan/g2plot-vue2-demo@7e1b25a](https://github.com/open-data-plan/g2plot-vue2-demo/commit/7e1b25a353cd9c6dcff105b57c5e5eb6e811074b)

你好，具体配置如下，https://codesandbox.io/s/sweet-snow-66p0s?file=/package.json

**Comment by kagawagao** [comment]
是因为没有启用 `composition-api` 导致的，参考 [composition-api](https://github.com/vuejs/composition-api)

**Comment by vvyman** [comment]
> 是因为没有启用 `composition-api` 导致的，参考 [composition-api](https://github.com/vuejs/composition-api)

it works，十分感谢～🙏
