### ISSUE TITLE
[Bug]nuxt3

### ISSUE THREAD

**Issue by waset** [open-data-plan/g2plot-vue#703]
I tried various introduction methods in `nuxt3`, but they all failed. 
Sorry, I can't provide code evidence because I'm trying to use it according to the official documents of [g2plot](https://g2plot.antv.vision/en/docs/manual/getting-started).

**Comment by kagawagao** [comment]
a mini showcase please

**Comment by kagawagao** [comment]
I've created a nuxt3 demo

[![Edit modest-thunder-tcvqj7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-thunder-tcvqj7?fontsize=14&hidenavigation=1&theme=dark)

**Comment by waset** [comment]
> 我创建了一个 nuxt3 演示
> 
> [![编辑谦雷-tcvqj7](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/modest-thunder-tcvqj7?fontsize=14&hidenavigation=1&theme=dark)

Sorry, I just added a demo after I was busy. We do the same [work](https://github.com/WeCases/opd-g2plot-vue.git), but the problem is `bulid`

**Comment by waset** [comment]
@kagawagao It seems that it has not been solved. It is suggested to reopen the issues.

**Comment by kagawagao** [comment]
nuxt3 use `Native ESM` cause runtime error, you can solve it follow nuxt [docs](https://v3.nuxtjs.org/concepts/esm/#troubleshooting-esm-issues)

```ts
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt3';

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  vite: {
    plugins: [],
  },
  build: {
    transpile: ['@opd/g2plot-vue', 'lodash'],
  },
});
```
